[package]
name = "simple_max31865"
version = "0.1.0"
authors = ["Alan Robertson <alanr@unix.sh>"]
keywords = ["embedded-hal-v1", "rtd-sensor", "max31865", "spi"]
categories = ["embedded", "no-std", "hardware-support"]
description = "Easy to Use driver for the MAX31865 RTD to Digital converter"
documentation = "https://github.com/Alan-R/simple-max31865"
homepage = "https://github.com/Alan-R/simple-max31865"
repository = "https://github.com/Alan-R/simple-max31865"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
rppal = { version = "0.17", features = ["embedded-hal"] }  # Enables embedded-hal v1 traits for SpiBus, OutputPin, etc.

[features]
mock = [] # to enable mock hardware emulation
no_fp = [] # to disable APIs that return floating point
